#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School

sudo curl localhost
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart