#!/usr/bin/env bash
# Configures Nginx to perform a 301 redirection

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

rm /etc/nginx/sites-enabled/default
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
