#!/usr/bin/env bash
# Install and configure Hproxy on your lb-01 server

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
sed -i '/errorfile 504/a listen seyi-kuforiji' /etc/haproxy/haproxy.cfg
sed -i '/listen seyi-kuforiji/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 19257-web-01 3.238.133.89:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 652-web-01 3.238.133.89:80 check/a         server 19257-web-02 34.239.158.255:80 check' /etc/haproxy/ha>sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
