#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic

# install ufw
sudo apt-get update
sudo apt-get install ufw

# block all incoming traffic
sudo ufw default deny incoming

# allow all outgoing traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# enable firewall
sudo ufw enable